Function to get the public IP from various sources

diff --git a/update b/update
--- a/update
+++ b/update
@@ -1,7 +1,10 @@
 #!/bin/bash
 
-# Check if a string is a valid IPv4 using regex
-is_valid_ipv4() {
+# Default value for the public IP
+ip=""
+
+# Function to check if a string is a valid IPv4 using regex
+_is_valid_ipv4() {
     local ip="$1"
     rx='([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])'  # A number from 0 to 255
     if [[ "$ip" =~ ^$rx\.$rx\.$rx\.$rx$ ]]; then
@@ -11,13 +14,30 @@ is_valid_ipv4() {
     fi
 }
 
-# List of IP addresses to validate
-IP_LIST=("10.0.0.1" "192.168.1.100" "172.16.0.254" "256.0.0.1" "192.168.1.300" "172.16.0.256")
+# Function to get the public IP from various sources
+_get_public_ip() {
+    readonly URLS=(
+        "https://icanhazip.com"
+        "https://api.ipify.org"
+        "http://icanhazip.com"
+        "http://api.ipify.org"
+        "http://myexternalip.com/raw"
+    )
 
-for ip in "${IP_LIST[@]}"; do
-    if is_valid_ipv4 "$ip"; then
-        echo "Valid: $ip"
-    else
-        echo "Invalid: $ip"
-    fi
-done
+    for url in "${URLS[@]}"; do
+        ip=$(wget -qO- "$url")  # Get the public IP using wget
+        ip=${ip//[[:space:]]/}  # Remove all whitespace (including internal spaces)
+        if _is_valid_ipv4 "$ip"; then
+            break
+        fi
+    done
+}
+
+# Get the public IP, if failed then exit program
+_get_public_ip
+if [ -z "$ip" ]; then
+    echo "Could not get the public IP"
+    exit 1
+else
+    echo "The public IP is: $ip"
+fi
