Add setup file

diff --git a/update b/update
--- a/update
+++ b/update
@@ -6,7 +6,7 @@ _read_config() {
 
     # Check if the config file exists
     if [ ! -f "$THE_CONFIG_FILE" ]; then
-        echo "The config file does not exist. Please run \`bash setup\` or create file .config manually."
+        echo "The config file does not exist. Please run \`bash setup\` or create file .config manually." >&2
         echo "$TIME - The config file does not exist" >> $LOG_FILE
         exit 1
     fi
@@ -28,7 +28,7 @@ _read_config() {
 
     # Check if the config file is set properly
     if [[ -z "$N_USERNAME" || -z "$N_PASSWORD" || -z "$N_HOSTNAME" ]]; then
-        echo "The config file is not set properly. Please run \`bash setup\` or create file .config manually."
+        echo "The config file is not set properly. Please run \`bash setup\` or create file .config manually." >&2
         echo "$TIME - The config file is not set properly" >> $LOG_FILE
         exit 1
     fi
@@ -92,7 +92,7 @@ ip=""
 # Get the public IP, if failed then exit program
 _get_public_ip
 if [ -z "$ip" ]; then
-    echo "Could not get the public IP"
+    echo "Could not get the public IP" >&2
     echo "$TIME - Could not get the public IP" >> $LOG_FILE
     exit 1
 else
